language: node_js
node_js: 10.13.0
install:
    - uname -a
    - wget https://github.com/gohugoio/hugo/releases/download/v0.51/hugo_0.51_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - hugo version
    - rm -rf blog
    - ls
    - pwd

script:
    - hugo
    - gulp
    - echo 'Hugo build done!'
before_script:
    - git config --global user.email "incomparable9527@foxmail.com"
    - git config --global user.name "Fan"
after_success:
    - git clone https://${ACCESS_TOKEN}@github.com/Fantasy9527/alili.tech.git
    # - rm -rf container/*
    # - cp -r blog/* container 
    - ls
    - cd public
    - ls
    - git add .
    - git commit -m 'Travis upate blog'
    - git push -u origin gh-pages -f
    - curl -d "" ${DEPLOY_API}
