language: node_js
node_js: --lts
before_script:
  - git config user.name "Fan"
  - git config user.email "incomparable9527@foxmail.com"
  - sed -i'' "s~https://github.com/Fantasy9527/alili.tech.git~https://${ACCESS_TOKEN}@github.com/Fantasy9527/alili.tech.git~" _config.yml
  - sed -i'' "~https://${CODING_ACCESS_TOKEN}@git.dev.tencent.com/incomparable9527/incomparable9527.coding.me.git~" _config.yml
script:
  - npm run deploy
