# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Alili
subtitle: 前端大爆炸! - WEB BANG! BANG!! BANG!!!
description: 前端大爆炸,一个前端技术分享平台.为广大前端开发技术人员提供最新前端技术资讯与解决方案.
keywords: Alili,前端大爆炸,WEB BANG BANG BANG,web前端博客,前端模块化,前端工程,富应用开发,html5上传,前端数据监控,性能优化,网页制作,前端,js,html5,css,踩坑小报告,微前端,树莓派,前端开发,区块链,网络,Mongodb,Vue.js,Angular.js,node.js
author: Fan
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
abbrlink:
  alg: crc32  #support crc16(default) and crc32
  rep: hex    #support dec(default) and hex

url: https://alili.tech
root: /
permalink: archive/:abbrlink/
permalink_defaults:


# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: ['google541e1b3422feb984.html','examples/','README.md']

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: hexo-theme-modernist
theme: cactus-dark


# 自动生成sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

#压缩
# neat_enable: true


baidu_url_submit:
  count: 60 ## 提交最新的一个链接
  host: alili.tech ## 在百度站长平台中注册的域名
  token: QsL3LjB4I2GLWGbj ## 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt ## 文本文档的地址， 新链接会保存在此文本文档里
  xz_appid: '1613049289050283'
  xz_token: 'PEQAd9p3kMBAzNjY'
  xz_count: 25

pwa:
  manifest:
    path: /manifest.json
    body:
      "name": "WEB BANG! BANG!! BANG!!!"
      "short_name": "前端大爆炸"
      "theme_color": "#1d1f21"
      "background_color": "#1d1f21"
      "display": "standalone"
      "Scope": "/"
      "start_url": "/"
      icons:
        - src: https://alili.tech/images50x50.png
          sizes: 144x144
          type: image/png
        - src: https://alili.tech/images50x50.png
          sizes: 128x128
          type: image/png
        - src: https://alili.tech/images50x50.png
          sizes: 96x96
          type: image/png
  serviceWorker:
    path: /sw.js
    preload:
      urls:
        - /
      posts: 5
    opts:
      networkTimeoutSeconds: 5
    routes:
      - pattern: !!js/regexp /.*\.(min.css|min.js|woff2|ttf|jpg|jpeg|png|gif)$/
        strategy: cacheFirst
  priority: 5  

addlink:
  before_text: '<h2> 本文链接：</h2>' # text before the post link
  after_text: '' # text after the post link


recommended_posts:
  server: https://api.truelaurel.com #后端推荐服务器地址
  timeoutInMillis: 10000 #服务时长，超过此时长，则使用离线推荐模式
  internalLinks: 5 #内部文章数量
  externalLinks: 3 #外部文章数量
  fixedNumber: 8
  autoDisplay: true  #自动在文章底部显示推荐文章
  excludePattern: []
  titleHtml: <h1>相关文章</h1> #自定义标题

# nofollow:
# 	enable: true
# 	exclude:
#     - alili.tech

# toJson:
#   enablePagination: ture # chunk the index.json array based on per_page in _config.yml
#   configs: false # donnot generate the global and theme config api.
#   pages:
#     selectors:
#       - title # string selector
#       - date
#       - updated
#       - comments
#       - excerpt
#       - more
#       - source
#       - permalink
#       - photos
#       - link
#     extracts: [content]
#   posts:
#     selectors:
#       - title
#       - date
#       - updated
#       - comments
#       - excerpt
#       - more
#       - source
#       - permalink
#       - photos
#       - link
#       - {path: tags, childrenSelectors: ['name', 'slug', 'permalink']} # object selector
#       - {path: categories, childrenSelectors: ['name', 'slug', 'permalink']}
#     extracts: [content]
#     raw: true
#     text: false
#   tags: true # using default config
#   categories: true

# Deployment  站点部署到github要配置这里, 非常重要
## Docs: http://hexo.io/docs/deployment.html
deploy:
- type: baidu_url_submitter # 百度
- type: baidu_xz_url_submitter # 百度熊掌号


- type: git    #部署类型
  repo:
    github:  https://github.com/Fantasy9527/alili.tech.git  
    coding:  https://git.coding.net/incomparable9527/incomparable9527.coding.me.git 
  branch: master

- type: tencent_deploy # 腾讯服务器
