menu:
  Home: /
  Archives: /archives
  About: /about
## rss: /atom.xml

archive_date_format: MMM DD
fancybox: true

disqus_shortname: alili-tech
duoshuo_shortname:


google_analytics:
favicon: /favicon.ico
